//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public Feedback()
        {
            this.Reasons = new HashSet<Reason>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int CourseId { get; set; }
        public int StudentId { get; set; }
        public int MoodId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Mood Mood { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<Reason> Reasons { get; set; }
    }
}
