//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mood
    {
        public Mood()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Reasons = new HashSet<Reason>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Reason> Reasons { get; set; }
    }
}
