//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public Reason()
        {
            this.FeedbackReasons = new HashSet<FeedbackReason>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public int MoodId { get; set; }
        
        public virtual Mood Mood { get; set; }
        public virtual ICollection<FeedbackReason> FeedbackReasons { get; set; }
    }
}
